package com.example.nexus.ui.screens.movies

object MoviesCategories {
    val moviesCategories = listOf(
        MoviesCategory.UpComing,
        MoviesCategory.NewHistory,
        MoviesCategory.Thriller,
        MoviesCategory.Family,
        MoviesCategory.ActionAndDrama,
        MoviesCategory.ActionComedy,
        MoviesCategory.OnlyNexus,
        MoviesCategory.NowPlaying,
        MoviesCategory.Comedy,
        MoviesCategory.Action,
        MoviesCategory.ActionAndThriller,
        MoviesCategory.DramaAndDocumentary,
        MoviesCategory.Terror,
        MoviesCategory.SciFiAndFantasy,
        MoviesCategory.Thriller2,
        MoviesCategory.ScienceFiction,
        MoviesCategory.Crime,
        MoviesCategory.TvMovie,
        MoviesCategory.WarAndThriller,
        MoviesCategory.DramaArgentina,
        MoviesCategory.Comedy2,
        MoviesCategory.Horror,
        MoviesCategory.ActionKorea,
        MoviesCategory.Animation,
        MoviesCategory.Drama2,
        MoviesCategory.ActionAndSciFi,
        MoviesCategory.TaqAction,
        MoviesCategory.Romance,
        MoviesCategory.Trending,
        MoviesCategory.Popular,
        MoviesCategory.War,
        MoviesCategory.Mystery,
        MoviesCategory.Adventure,
        MoviesCategory.Fantasy,
        MoviesCategory.Western,
    )
}
