package com.example.nexus.ui.screen


object CategoriasNetflix {
    val seriesSuspenso = "Series de Suspenso para maratonear premiadas"
    val seleccionDeHoy = "Nuestra selección de hoy para ti"
    val diezSeriesPopulares = "Las 10 series más populares en Argentina hoy"
    val soloEnNetflix = "Solo en Netflix"
    val peliculasYseriesEnEspañol = "Películas y series en español"
    val todaLaAccion = "Toda la acción"
    val nuevoEnNetflix = "Lo nuevo en Netflix"
    val seriesRomanticas = "Series Romanticas"
    val peliculasHollywoodEspañol = "Películas de Holliwood dobladas al español"
    val diezPeliculasPopularesArgentina = "Las 10 películas más populares en Argentina hoy"
    val proximaHistoria = "Tu próxima historia"
    val peliculasAccionAventura = "Peliculas de acción y aventura"
    val seriesAdolescentes = "Series de adolescentes sobre la transición a la edad adulta"
    val seriesDramaticasEmotivas = "Series dramáticas emotivas"
    val seriesEEUU = "Series de EE. UU."
    val heroesDeAccion = "Héroes de acción"
    val SeriesMaratonear = "Series para maratonear"
    val romancesInolvidables = "Romances Inolvidables"
    val peliculasDeTerror = "Películas de terror"
    val creemosQueTeEncantarán = "Creemos que estos te encantarán"
    val seriesAsiaticasRomanticas = "Series asiáticas románticas"
    val directoCorazon = "Directo al corazón"
    val peques = "Para ver con peques no tan peques"
    val planesLargoPlazo = "Planes a largo plazo"
    val loMasBuscados = "Los más buscados"
    val atrapantes = "Atrapantes de principio a fin"
    val seriesVenganza = "Series de venganza"
    val peliculasTaquilleras = "Películas taquilleras"
    val peliculasReir = "Películas para reír"
    val seriesSombrías = "Series sombrías"
    val películasInfantiles = "Películas infantiles"
    val seriesDramaticas = "Series Dramáticas"
    val seriesTerror = "Series de sci-fi y terror"
    val holliwoodAtuPantalla = "De holliwood a tu pantalla"

}