package com.example.nexus.ui.screen.home

val homeCategories = listOf(
    HomeCategory.ThrillingSeries,
    //HomeCategory.TodaySelection,
    //HomeCategory.Top10SeriesArgentina,
    //HomeCategory.OnlyOnNetflix,
    //HomeCategory.SpanishContent,
    HomeCategory.AllAction,
    //HomeCategory.NewReleases,
    HomeCategory.RomanticSeries,
    //HomeCategory.DubbedHollywood,
    //HomeCategory.Top10MoviesArgentina,
    HomeCategory.NextStory,
    HomeCategory.ActionAdventure,
    HomeCategory.TeenSeries,
    HomeCategory.EmotionalDramas,
    //HomeCategory.USASeries,
    HomeCategory.ActionHeroes,
    //HomeCategory.MarathonSeries,
    HomeCategory.UnforgettableRomance,
    HomeCategory.HorrorMovies,
    HomeCategory.RecommendedForYou,
    //HomeCategory.AsianRomanticSeries,
    HomeCategory.HeartfeltContent,
    //HomeCategory.FamilyFriendly,
    //HomeCategory.LongTermPlans,
    //HomeCategory.TrendingNow,
    HomeCategory.AddictiveContent,
    HomeCategory.RevengeSeries,
    //HomeCategory.BlockbusterMovies,
    HomeCategory.ComedyMovies,
    HomeCategory.DarkSeries,
    HomeCategory.KidsMovies,
    HomeCategory.DramaSeries,
    HomeCategory.SciFiHorrorSeries,
    HomeCategory.HollywoodOnYourScreen
)